# Veyloria test world preset
motd=Veyloria Test Realm
spawn-protection=0
view-distance=12
simulation-distance=12
difficulty=normal
allow-flight=true
pvp=false
online-mode=false
level-type=minecraft:flat
generate-structures=false
generator-settings={"layers":[{"height":1,"block":"minecraft:bedrock"},{"height":2,"block":"minecraft:dirt"},{"height":1,"block":"minecraft:grass_block"}],"biome":"minecraft:plains","structures":{}}
